import SentwiseMail
import XCTest
@testable import Sentwise

/// Tests for the pure reply-worthiness evaluator (item 17). These heuristics are
/// load-bearing — a false skip silently loses a real reply — so they are
/// exercised exhaustively here with no IMAP involved. The bias is conservative:
/// when in doubt, the message must be `.worthy`.
final class ReplyWorthinessTests: XCTestCase {

    private func evaluate(
        sender: String?,
        headers: MailHeaderFields = MailHeaderFields()
    ) -> ReplyWorthinessVerdict {
        ReplyWorthiness.evaluate(ReplyWorthinessSignals(senderEmail: sender, headers: headers))
    }

    private func evaluate(
        senders: [String?],
        headers: MailHeaderFields = MailHeaderFields()
    ) -> ReplyWorthinessVerdict {
        ReplyWorthiness.evaluate(ReplyWorthinessSignals(senderEmails: senders, headers: headers))
    }

    private func evaluate(
        from: String?,
        replyTo: String?,
        headers: MailHeaderFields = MailHeaderFields()
    ) -> ReplyWorthinessVerdict {
        ReplyWorthiness.evaluate(
            ReplyWorthinessSignals(fromEmail: from, replyToEmail: replyTo, headers: headers)
        )
    }

    // MARK: - Worthy (conservative default)

    func testPlainPersonalMailIsWorthy() {
        XCTAssertEqual(evaluate(sender: "alice@example.com"), .worthy)
    }

    func testWorthyWhenNoSignalsAtAll() {
        XCTAssertEqual(evaluate(sender: nil), .worthy)
    }

    func testOrdinaryContentTypeIsWorthy() {
        let headers = MailHeaderFields(contentType: "multipart/alternative; boundary=abc")
        XCTAssertEqual(evaluate(sender: "bob@example.com", headers: headers), .worthy)
    }

    func testAutoSubmittedNoIsWorthy() {
        // RFC 3834: `no` explicitly means not automated.
        let headers = MailHeaderFields(autoSubmitted: "no")
        XCTAssertEqual(evaluate(sender: "bob@example.com", headers: headers), .worthy)
    }

    func testSenderContainingReplyWordIsNotFalselySkipped() {
        // "reply" alone must not trip the no-reply heuristic.
        XCTAssertEqual(evaluate(sender: "reply-team@example.com"), .worthy)
        XCTAssertEqual(evaluate(sender: "andrew@example.com"), .worthy)
    }

    // MARK: - No-reply senders

    func testNoReplySenderVariantsAreSkipped() {
        for address in [
            "no-reply@example.com",
            "noreply@example.com",
            "donotreply@example.com",
            "do-not-reply@example.com",
            "No_Reply@Example.com",
            "notifications@github.com",
            "mailer-daemon@example.com",
            "postmaster@example.com",
            "bounces+tag@example.com",
            "github-noreply@example.com"
        ] {
            XCTAssertEqual(
                evaluate(sender: address),
                .skip(.noReplySender),
                "expected \(address) to be a no-reply sender"
            )
        }
    }

    func testNoReplyDomainDoesNotTriggerOnLocalPart() {
        // The domain containing "noreply" must not skip a real local part.
        XCTAssertEqual(evaluate(sender: "alice@noreply-mailer.example.com"), .worthy)
    }

    // MARK: - Bulk / list mail

    func testListIdIsSkipped() {
        let headers = MailHeaderFields(listID: "Widgets <widgets.example.com>")
        XCTAssertEqual(evaluate(sender: "news@example.com", headers: headers), .skip(.bulkOrListMail))
    }

    func testListUnsubscribeIsSkipped() {
        let headers = MailHeaderFields(listUnsubscribe: "<mailto:unsub@example.com>")
        XCTAssertEqual(evaluate(sender: "news@example.com", headers: headers), .skip(.bulkOrListMail))
    }

    func testPrecedenceBulkListJunkAreSkipped() {
        for value in ["bulk", "list", "junk", "Bulk", "  LIST  "] {
            let headers = MailHeaderFields(precedence: value)
            XCTAssertEqual(
                evaluate(sender: "news@example.com", headers: headers),
                .skip(.bulkOrListMail),
                "expected precedence \(value) to be bulk/list mail"
            )
        }
    }

    func testPrecedenceFirstClassIsWorthy() {
        let headers = MailHeaderFields(precedence: "first-class")
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .worthy)
    }

    // MARK: - Automated notifications

    func testAutoSubmittedAutoGeneratedIsSkipped() {
        let headers = MailHeaderFields(autoSubmitted: "auto-generated")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    func testAutoSubmittedWithParametersIsSkipped() {
        let headers = MailHeaderFields(autoSubmitted: "auto-replied; owner")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    func testAutoResponseSuppressIsSkipped() {
        let headers = MailHeaderFields(autoResponseSuppress: "All")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    func testAutoResponseSuppressNoneIsWorthy() {
        for value in ["None", " none ", "NONE", "DR", "RN", "NRN", "DR, RN, NRN"] {
            let headers = MailHeaderFields(autoResponseSuppress: value)
            XCTAssertEqual(
                evaluate(sender: "alice@example.com", headers: headers),
                .worthy,
                "expected \(value) to be non-automated"
            )
        }
    }

    func testAutoResponseSuppressMixedValueIsSkipped() {
        let headers = MailHeaderFields(autoResponseSuppress: "None, All")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    // MARK: - Calendar invites

    func testCalendarContentTypeIsSkipped() {
        let headers = MailHeaderFields(contentType: "text/calendar; method=REQUEST; charset=UTF-8")
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .skip(.calendarInvite))
    }

    func testCalendarContentTypeWithoutRequestMethodIsWorthy() {
        let headers = MailHeaderFields(contentType: "text/calendar; charset=UTF-8")
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .worthy)
    }

    func testNestedCalendarBodyContentTypeIsSkipped() {
        let headers = MailHeaderFields(
            contentType: "multipart/alternative; boundary=abc",
            bodyContentTypes: ["multipart/alternative", "text/plain", "text/calendar; method=REQUEST"]
        )
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .skip(.calendarInvite))
    }

    func testCalendarAttachmentContentTypeIsWorthy() {
        let headers = MailHeaderFields(
            contentType: "multipart/mixed; boundary=abc",
            bodyContentTypes: ["multipart/mixed", "text/plain", "application/ics"]
        )
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .worthy)
    }

    func testMultipartWithoutCalendarBodyContentTypeIsWorthy() {
        let headers = MailHeaderFields(
            contentType: "multipart/alternative; boundary=abc",
            bodyContentTypes: ["multipart/alternative", "text/plain", "text/html"]
        )
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .worthy)
    }

    func testCalendarInviteBeatsAutomationSignals() {
        // A calendar invite from a real person is a calendar invite first.
        let headers = MailHeaderFields(
            autoSubmitted: "auto-generated",
            contentType: "text/calendar; method=REQUEST"
        )
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .skip(.calendarInvite))
    }

    // MARK: - Both-address evaluation (item 66)

    func testNoReplyOnReplyToOrKnownProviderFromIsSkipped() {
        // The GitHub `notifications@github.com` -> `reply.github.com` pattern named
        // in item 66 is a known provider-routing exception.
        XCTAssertEqual(
            evaluate(from: "notifications@github.com", replyTo: "reply+abc@reply.github.com"),
            .skip(.noReplySender)
        )
        // A no-reply `Reply-To` behind a human `From` still skips.
        XCTAssertEqual(
            evaluate(from: "alice@example.com", replyTo: "no-reply@example.com"),
            .skip(.noReplySender)
        )
    }

    func testRoutableReplyToPreventsGenericFromNoReplySkip() {
        XCTAssertEqual(
            evaluate(from: "notifications@ats.example", replyTo: "recruiter@company.example"),
            .worthy
        )
        XCTAssertEqual(
            evaluate(from: "no-reply@vendor.example", replyTo: "support@vendor.example"),
            .worthy
        )
    }

    func testBothPersonalAddressesAreWorthy() {
        XCTAssertEqual(evaluate(senders: ["alice@example.com", "alice.work@example.com"]), .worthy)
    }

    func testNilAndEmptyAddressesAreIgnored() {
        XCTAssertEqual(evaluate(senders: [nil, "alice@example.com"]), .worthy)
        XCTAssertEqual(evaluate(senders: [nil, nil]), .worthy)
    }

    // MARK: - Transactional senders (item 66)

    func testTransactionalSendersFromSnapshotAreSkipped() {
        // Every leaked sender from the 2026-08-20 pending-drafts snapshot named in
        // item 66. All report `.automatedNotification` (machine-issued mail).
        for address in [
            "invoice+statements@stripe.com",       // Stripe/Anthropic receipt (From)
            "invoice+statements@anthropic.com",
            "receipts@stripe.com",
            "auto-confirm@amazon.com",             // Amazon order confirmation
            "shipment-tracking@amazon.com",        // Amazon shipping
            "order-update@amazon.com",             // Amazon order update
            "budgets@costalerts.amazonaws.com",    // AWS budget alert (local part)
            "someteam@applytojob.com"              // recruiting blast (domain)
        ] {
            XCTAssertEqual(
                evaluate(sender: address),
                .skip(.automatedNotification),
                "expected \(address) to be a transactional/automated sender"
            )
        }
    }

    func testGitHubReceiptCaughtViaFromNotReplyTo() {
        // GitHub: automated `From`, routable `Reply-To`. Must be caught by From.
        XCTAssertEqual(
            evaluate(from: "notifications@github.com", replyTo: "reply+deadbeef@reply.github.com"),
            .skip(.noReplySender)
        )
    }

    func testAWSCostAlertsDomainIsSkippedEvenWithoutTokenLocalPart() {
        XCTAssertEqual(evaluate(sender: "anything@costalerts.amazonaws.com"), .skip(.automatedNotification))
        // Dot-boundary subdomain of an automated domain also matches.
        XCTAssertEqual(evaluate(sender: "x@notify.applytojob.com"), .skip(.automatedNotification))
    }

    // MARK: - Transactional negatives (no over-skip)

    func testGenuineHumanTeamInboxesStillDraft() {
        // The conservative bias: bare `support@`/`billing@`, and human aliases
        // that merely contain a transactional word, must still be worthy.
        for address in [
            "support@vendor.com",
            "billing@vendor.com",
            "invoice@accounting-firm.example",
            "statements@bank.example",
            "orders@smallshop.example",
            "invoice-questions@vendor.com",   // contains "invoice" but not exact
            "orderdesk@vendor.com",           // contains "order" but not a token
            "alerta@example.com",             // contains "alert" but not exact
            "confirmation-team@example.com",  // "confirm"-ish human alias
            "alice@applytojobs.com"           // look-alike domain, not applytojob.com
        ] {
            XCTAssertEqual(
                evaluate(sender: address),
                .worthy,
                "expected \(address) to remain worthy (no over-skip)"
            )
        }
    }

    func testLookAlikeAutomatedDomainIsNotMatched() {
        // Substring/look-alike must not match: only exact domain or dot-boundary
        // subdomain (mirrors the SenderRules discipline, item 18).
        XCTAssertEqual(evaluate(sender: "x@notapplytojob.com"), .worthy)
        XCTAssertEqual(evaluate(sender: "x@applytojob.com.evil.com"), .worthy)
    }

    // MARK: - Precedence of reasons

    func testNoReplySenderTakesPrecedenceOverListHeaders() {
        let headers = MailHeaderFields(listUnsubscribe: "<mailto:unsub@example.com>")
        XCTAssertEqual(evaluate(sender: "no-reply@example.com", headers: headers), .skip(.noReplySender))
    }

    func testHeaderBulkSignalTakesPrecedenceOverTransactionalSender() {
        // A receipt that also carries List-Unsubscribe reports bulk (header check
        // runs before the sender-based transactional check).
        let headers = MailHeaderFields(listUnsubscribe: "<mailto:unsub@stripe.com>")
        XCTAssertEqual(evaluate(sender: "receipts@stripe.com", headers: headers), .skip(.bulkOrListMail))
    }
}
